name       : qt6-quicktimeline
version    : 6.3.0
release    : 3
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qtquicktimeline-everywhere-src-6.3.0.tar.xz : 9ff0a931159efc6be5bd9f8a1e4a16a70e2dab37cf22ad85c6d330ccfdf31c1a
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Enables keyframe-based animations and parameterization for Qt6
description: |
    The Qt Quick Timeline module enables keyframe-based animations and parameterization. This module is directly supported by Qt Design Studio and Qt Quick Designer, with a timeline editor to create keyframe-based animations.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
