name       : qt6-quicktimeline
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtquicktimeline-everywhere-src-6.2.1.tar.xz : 55f571ee2adcf7b12473b8df8b9e2e60d3778d8c9055c301d4c11d7c2327de63
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Enables keyframe-based animations and parameterization for Qt6
description: |
    The Qt Quick Timeline module enables keyframe-based animations and parameterization. This module is directly supported by Qt Design Studio and Qt Quick Designer, with a timeline editor to create keyframe-based animations.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
