name       : qt6-quicktimeline
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qtquicktimeline-everywhere-src-6.2.2.tar.xz : 939d5479b035f674dd669b3e084ec9688eaea62763d2a7ad134630ff20efd479
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Enables keyframe-based animations and parameterization for Qt6
description: |
    The Qt Quick Timeline module enables keyframe-based animations and parameterization. This module is directly supported by Qt Design Studio and Qt Quick Designer, with a timeline editor to create keyframe-based animations.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
